export const PDF_LABELS = {
  fr: {
    title: 'ATHENA SURVEILLANCE - Rapport',
    date: 'Date',
    accessPoint: 'Point d\'accès',
    supervisor: 'Chef de poste',
    visitorsSection: 'VISITEURS',
    vehiclesSection: 'VÉHICULES',
    visitorName: 'Nom du visiteur',
    personVisited: 'Personne visitée',
    cinNumber: 'N° CIN',
    vehiclePlate: 'Immatriculation',
    company: 'Société',
    entryTime: 'HE',
    exitTime: 'HS',
    destination: 'Destination',
    observations: 'Observations',
    announced: 'Annoncé',
    vehicleType: 'Type de véhicule',
    driverName: 'Chauffeur',
    plate: 'Immatriculation',
    voucherNumber: 'N° de bon',
  },
  ar: {
    title: 'أثينا للمراقبة - تقرير',
    date: 'التاريخ',
    accessPoint: 'نقطة الدخول',
    supervisor: 'رئيس المركز',
    visitorsSection: 'الزوار',
    vehiclesSection: 'المركبات',
    visitorName: 'اسم الزائر',
    personVisited: 'الشخص المزار',
    cinNumber: 'رقم البطاقة',
    vehiclePlate: 'رقم اللوحة',
    company: 'الشركة',
    entryTime: 'وقت الدخول',
    exitTime: 'وقت الخروج',
    destination: 'الوجهة',
    observations: 'ملاحظات',
    announced: 'معلن',
    vehicleType: 'نوع المركبة',
    driverName: 'السائق',
    plate: 'رقم اللوحة',
    voucherNumber: 'رقم القسيمة',
  },
};
